# set color 
set $active_border #3BC1A8
set $inactive_border #0C7779
set $background #ffffff
set $text #ffffff
set $indicator #005461
# title bar
default_floating_border pixel 2
default_border pixel 2
# class
client.focused $active_border $background $text $active_border $active_border
client.focused_inactive $inactive_border $background $text $inactive_border $inactive_border
client.unfocused $inactive_border $background $text $inactive_border $inactive_border
client.focused_tab_title $active_border $background $text $inactive_border $active_border
#border
corner_radius 4

# Gaps
gaps inner 2px
gaps outer 2px
